main_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions

urlpatterns = [
    # Routes will be added here
    # path('', views.home, name='home'),
    path('', views.Home.as_view(), name='home'),
    path('plants/', views.plant_index, name='plant-index'),
    path('plants/<int:plant_id>/', views.plant_detail, name='plant-detail'), # can change the link address
    path('plants/create/', views.PlantCreate.as_view(), name='plant-create'),
    path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant-update'),
    path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant-delete'),
    path(
        'plants/<int:plant_id>/add-care/', 
        views.add_care, 
        name='add-care'
    ),
    path('supplies/create/', views.SupplyCreate.as_view(), name='supply-create'),
    path('supplies/<int:pk>/', views.SupplyDetail.as_view(), name='supply-detail'),
    path('supplies/', views.SupplyList.as_view(), name='supply-index'),

    path('supplies/<int:pk>/update/', views.SupplyUpdate.as_view(), name='supply-update'),
    path('supplies/<int:pk>/delete/', views.SupplyDelete.as_view(), name='supply-delete'),

    # to associate a plant with a supply
    path('plants/<int:plant_id>/associate-supply/<int:supply_id>/', views.associate_supply, name='associate-supply'),
    path('plants/<int:plant_id>/remove-supply/<int:supply_id>/', views.remove_supply, name='remove-supply'),
    path('accounts/signup/', views.signup, name='signup'), #no generic view available for this function

]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), # Mount the app's routes at the root URL
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# A tuple of 2-tuples added above our models
CARE_TIMES = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)
#^the value that will be stored in the database,  the human-friendly “display” value

class Supply(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20)
    color = models.CharField(max_length=20, blank=True, null=True)
    # blank=True: Allows the field to be left blank in forms (Django admin, etc.).
    # null=True: Allows the database to store NULL for this field.

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('supply-detail', kwargs={'pk': self.id})

# Create your models here.
class Plant(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # Many-to-Many relationship with supplies
    supplies = models.ManyToManyField(Supply)
    # Add the foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #^if plant get deleted its associated user get delete too
    
    def __str__(self):
        return self.name
    
    # Define a method to get the URL for this particular plant instance
    def get_absolute_url(self):
        # Use the 'reverse' function to dynamically find the URL for viewing this plant's details
        return reverse('plant-detail', kwargs={'plant_id': self.id})
    
class Care(models.Model):
    date = models.DateField('Care date')
    time_of_day = models.CharField(
        max_length=1,
        choices=CARE_TIMES,
        default=CARE_TIMES[0][0] #M for morning
    )

    # Connect each care entry to a plant
    # Create a plant_id column for each care in the database
    #care belongs to a Plant
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    #^one-ton-many relationship, if a Plant record is deleted, all the child Care will be deleted
    def __str__(self):
        return f"{self.get_time_of_day_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']  # This line makes the newest cares appear first

main_app/forms.py
from django import forms
from .models import Care
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']  # email is optional unless you require it


class CareForm(forms.ModelForm):
    class Meta:
        model = Care
        fields = ['date', 'time_of_day']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from .models import Plant, Supply
from .forms import CareForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required # to protect view functions
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
# Import HttpResponse to send text-based responses
# from django.http import HttpResponse


# Define the home view function
# def home(request):
#     # Send a simple HTML response
#     # return HttpResponse('<h1>Hello ᓚᘏᗢ</h1>')
#     return render(request, 'home.html')
class Home(LoginView):
    template_name = 'home.html'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        # form = UserCreationForm(request.POST)
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('plant-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    # form = UserCreationForm()
    form = CustomUserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )

@login_required
def plant_index(request):
    # This reads ALL plants, not just the logged in user's plants
    # plants = Plant.objects.all()
    plants = Plant.objects.filter(user=request.user)
    # You could also retrieve the logged in user's plants like this
    # plants = request.user.plant_set.all()
    return render(request, 'plants/index.html', {
        'plants': plants
    })

@login_required
def plant_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    # supplies = Supply.objects.all() #fetch all supplies
    # Only get the supply the plant does not have
    supplies_plant_doesnt_have = Supply.objects.exclude(id__in = plant.supplies.all().values_list('id'))
    care_form = CareForm()
    return render(request, 'plants/detail.html', {
        'plant': plant, 'care_form': care_form,
        'supplies': supplies_plant_doesnt_have
        # 'supplies': supplies # pass suppliesto the template
    })

@login_required
def remove_supply(request, plant_id, supply_id):
    # Plant.objects.get(id=plant_id).supplies.remove(supply_id)
    # ^ this finds a particular plant and removes a record from the join
    # table with that plant's id and the id of the supply thus deleting the relationship/association
    # Look up the plant
    plant = Plant.objects.get(id=plant_id)
    # Look up the supply
    supply = Supply.objects.get(id=supply_id)
    # Remove the supply from the plant
    plant.supplies.remove(supply)
    return redirect('plant-detail', plant_id=plant_id)

class PlantCreate(LoginRequiredMixin, CreateView):
    model = Plant
    # fields = '__all__'
    # more explicit
    fields = ['name', 'species', 'description', 'age']
    # success_url = '/plants/' #static page

    # This inherited method is called when a
    # valid plant form is being submitted
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the plant
        # Let the CreateView do its job as usual
        return super().form_valid(form)



class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = Plant
    # things could be misspell
    fields = ['name', 'species', 'description', 'age']

class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/plants/' #make sense in this case, it's no longer in database after delete

@login_required
def add_care(request, plant_id):
    # create a ModelForm instance using the data in request.POST
    form = CareForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the plant_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.plant_id = plant_id
        new_feeding.save()
    return redirect('plant-detail', plant_id = plant_id)

class SupplyCreate(LoginRequiredMixin, CreateView):
    model = Supply
    fields = '__all__'

class SupplyList(LoginRequiredMixin, ListView):
    model = Supply

class SupplyDetail(LoginRequiredMixin, DetailView):
    model = Supply

class SupplyUpdate(LoginRequiredMixin, UpdateView):
    model = Supply
    fields = '__all__'
    # ['name', 'type', 'color']

class SupplyDelete(LoginRequiredMixin, DeleteView):
    model = Supply
    success_url = '/supplies/'

@login_required
def associate_supply(request, plant_id, supply_id):
    Plant.objects.get(id=plant_id).supplies.add(supply_id)
    return redirect('plant-detail', plant_id=plant_id)

main_app/templates/plants/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/plants/plant-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="plant-container">
  <div class="plant-img">
    <img src="" alt="" />
  </div>
  <div class="plant-details">
    <h1>{{ plant.name }}</h1>
    {% if plant.age <= 1 %}
    <p>A {{ plant.species }} seedling.</p>
    {% else %}
    <p>A {{ plant.age }} year old {{ plant.species }}.</p>
    {% endif %}
    <p><small>{{ plant.description }}</small></p>
  
    <div class="plant-actions">
        <a href="{% url 'plant-update' plant.id %}" class="btn warn">Edit</a>
        <a href="{% url 'plant-delete' plant.id %}" class="btn danger">Delete</a>
      </div>
</div>
</section>

<div class="cares-supply-container">
    <section class="cares">
      <div class="subsection-title">
        <h2>Cares</h2>
        <img
          src=""
          alt=""
        />
        <img 
            src="" 
            alt=""
        />
        <img
          src=""
          alt=""
        />
      </div>

      <h3>Add a Care</h3>
       <form
       action="{% url 'add-care' plant.id %}"
       method="post" 
       class="subsection-content" 
       autocomplete="off"
       >
        {% csrf_token %}
        {{care_form.as_p }}
        <button type="submit" class="btn submit">Add Care</button>
       </form>


    <h3>Past Care</h3>
    {% if plant.care_set.all.count %}
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Time of Day</th>
          </tr>
        </thead>
        <tbody>
          {% for care in plant.care_set.all %}
            <tr>
              <td>{{care.date}}</td>
              <td>{{care.get_time_of_day_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="subsection-content">
        <p>⚠️ {{plant.name}} has not been care for!</p>
      </div>
    {% endif %}


    </section>

    <section class="supplies">
      <div class="subsection-title">
        <h2>Supplies</h2>
        <img src="" alt="" />
        <img src="" alt="" />
        <img src="" alt="" />
      </div>

  <!-- displaying a plant's supplies -->
      <h3>{{ plant.name }}'s Supplies</h3>
        <div class="subsection-content">
          {% if plant.supplies.count %}
            {% for supply in plant.supplies.all %}
              <div class="supply-container">
                <div class="color-block" style="background-color: {{ supply.color }}"></div>
                <a href="{% url 'supply-detail' supply.id %}">
                  <p>A {{ supply.color }} {{ supply.name }}</p>
                </a>
                
                <form action="{% url 'remove-supply' plant.id supply.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Remove Supply</button>
                </form>

              </div>
            {% endfor %} 
          {% else %}
            <p class="no-supplies">{{plant.name}} doesn't have any supplies!</p>
          {% endif %}
  </div>




      <h3>Available Supplies</h3>
      <div class="subsection-content">
        {% if supplies.count %} 

        {% for supply in supplies.all %}
          <div class="supply-container">
            <div class="color-block" style="background-color: {{ supply.color }}"></div>
            {% if supply.color %}
              <p>{{ supply.color }} {{ supply.name }}</p>
            {% else %}
              <p> {{ supply.name }}</p>
            {% endif %}
            <form action="{% url 'associate-supply' plant.id supply.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn submit">Give Supply</button>
            </form>
          </div>
        {% endfor %}

        {% else %}
          <p class="all-supplies">{{plant.name}} already has all the available supplies 🥳</p>
        {% endif %}

      </div>
    </section>
    
  </div>
  

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/plants/plant-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Plant List</h1>
  <img
    src=""
    alt=""
  />
  <img
    src=""
    alt=""
  />
  <img
    src=""
    alt=""
  />
  <img
    src=""
    alt=""
  />
</section>

<section class="card-container">
  {% for plant in plants %}
  <div class="card">
    <a href="/plants/{{ plant.id }}">
    <div class="card-content">
      <div class="card-img-container">
        <img
          src=""
          alt=""
        />
      </div>
      <h2 class="card-title">{{ plant.name }}</h2>
      {% if plant.age <= 1 %}
      <p>A {{ plant.species }} seedling.</p>
      {% else %}
      <p>A {{ plant.age }} year old {{ plant.species }}.</p>
      {% endif %}
      <p><small>{{ plant.description }}</small></p>
    </div>
  </div>
  {% endfor %}
</section>

{% endblock %}